In [1]:
list1 = ["apple", "banana", "cherry"]
for index, element in enumerate(list1):
    print(index, element)

0 apple
1 banana
2 cherry


In [1]:
from pathlib import Path
path = Path("/datassd2/sswang/NFT_Search/CLIP/tests/test_consistency.py")
print(path.stem)
print(path.name)

test_consistency


In [5]:
import re

list1 = [
    "1. 0N1 Force is a Jasper with an Obsidian bob and PR Mask (Citrine). He wears a Track Jacket (Obsidian) and has a void head and void extra. His style is 4, strength is 4, and spirit is 5.",
    "2. 0N1 Force is a Jasper with a frown mouth and an eye shadow (Jasper) that matches his background. He wears a Track Jacket (Obsidian) and carries a PR Mask (Citrine) on his face. His bob (Obsidian) is void of hair, and he has a void extra. His strength is 4 and his spirit is 5, and his style is 4.",
    "3. 0N1 Force is a Jasper with a track jacket (Obsidian) and a bob (Obsidian) that matches his background. He wears a PR Mask (Citrine) on his face, and his void extra is void of information. His frown mouth and eye shadow (Jasper) match his background, and his style is 4. His strength is 4 and his spirit is 5."
]

list2 = [
        "A portrait of a young adult with a skull motif mask covering their face, donning a white 0N1 logo pin on a turquoise thermal hoodie, with squinting azurite eyes and a smirk on their citrine lips. Their dreads, made of bronzite, frame their face, and their head is adorned with an obsidian snapback.",
        "A photograph of a person with a background of citrine, wearing a thermally hoodie in turquoise, with a skull mask covering their face and squinting azurite eyes. Their mouth sports a smirk, and their head is adorned with an obsidian snapback, while their hair is made of dreads in bronzite.",
        "A portrait of a person with a skull mask covering their face, their eyes squinting azurite and their lips curved into a smirk. They wear a turquoise thermal hoodie and their hair is styled into dreads made of bronzite. Their face is framed by an obsidian snapback, and they have a white 0N1 logo"
    ]

new_lst = [re.sub(r'^\d+\. ', '', s) for s in list2]
print(type(new_lst))
for s in new_lst:
    print(s)

<class 'list'>
A portrait of a young adult with a skull motif mask covering their face, donning a white 0N1 logo pin on a turquoise thermal hoodie, with squinting azurite eyes and a smirk on their citrine lips. Their dreads, made of bronzite, frame their face, and their head is adorned with an obsidian snapback.
A photograph of a person with a background of citrine, wearing a thermally hoodie in turquoise, with a skull mask covering their face and squinting azurite eyes. Their mouth sports a smirk, and their head is adorned with an obsidian snapback, while their hair is made of dreads in bronzite.
A portrait of a person with a skull mask covering their face, their eyes squinting azurite and their lips curved into a smirk. They wear a turquoise thermal hoodie and their hair is styled into dreads made of bronzite. Their face is framed by an obsidian snapback, and they have a white 0N1 logo


In [1]:
list1 = ["apple", "banana", "cherry"]
list2 = ["1", "2", "3"]
list3 = ["a", "b", "c"]
for x, y, z in zip(list1, list2, list3):
    print(x, y, z)

apple 1 a
banana 2 b
cherry 3 c


In [11]:
import numpy as np
list4 = [
    ["apple", "banana", "cherry", "orange"],
    ["1", "2", "3", "4"],
    ["a", "b", "c", "d"]
]
new_list = [list(x) for x in zip(*list4)]
print(new_list)
for item in new_list:
    print(item)

[['apple', '1', 'a'], ['banana', '2', 'b'], ['cherry', '3', 'c'], ['orange', '4', 'd']]
['apple', '1', 'a']
['banana', '2', 'b']
['cherry', '3', 'c']
['orange', '4', 'd']


In [1]:
list1 = [["apple"], ["banana"], ["cherry"]]
list1.insert(1, ["orange"])
print(list1)

[['apple'], ['orange'], ['banana'], ['cherry']]


In [9]:
import torch
c = torch.tensor([[ 1, 2, 3], [-1, 1, 4]] , dtype=torch.float)
print(c.norm(dim=-1, keepdim=True))
c /= c.norm(dim=-1, keepdim=True)
print(c)

tensor([[3.7417],
        [4.2426]])
tensor([[ 0.2673,  0.5345,  0.8018],
        [-0.2357,  0.2357,  0.9428]])


In [8]:
c = torch.tensor([[ 1, 2, 3], [-1, 1, 4]] , dtype=torch.float)
torch.norm(c, dim=0, keepdim=True)

tensor([[1.4142, 2.2361, 5.0000]])

In [11]:
import numpy as np
print(np.array(list1).shape)

(3, 1, 768)


In [29]:
list_tensor1 = torch.tensor([
    [    
        [
            
            0.257080078125,
            0.128662109375,
            0.456298828125
            
        ],
        [   
            
            -0.515625,
            -0.33642578125,
            0.2396240234375
            
        ],
        [
            
            -1.1982421875,
            0.09759521484375,
            -0.292236328125
            
        ]
    ],
    [    
        [
            
            0.257080078125,
            0.128662109375,
            0.456298828125
            
        ],
        [   
            
            -0.515625,
            -0.33642578125,
            0.2396240234375
            
        ],
        [
            
            -1.1982421875,
            0.09759521484375,
            -0.292236328125
            
        ]
    ],
    [    
        [
            
            0.257080078125,
            0.128662109375,
            0.456298828125
            
        ],
        [   
            
            -0.515625,
            -0.33642578125,
            0.2396240234375
            
        ],
        [
            
            -1.1982421875,
            0.09759521484375,
            -0.292236328125
            
        ]
]
])

print(list_tensor1.shape)


torch.Size([3, 3, 3])


In [30]:
combined_tensor = torch.stack(tuple(list_tensor1), dim=1)

print(combined_tensor.shape)
print(combined_tensor)

torch.Size([3, 3, 3])
tensor([[[ 0.2571,  0.1287,  0.4563],
         [ 0.2571,  0.1287,  0.4563],
         [ 0.2571,  0.1287,  0.4563]],

        [[-0.5156, -0.3364,  0.2396],
         [-0.5156, -0.3364,  0.2396],
         [-0.5156, -0.3364,  0.2396]],

        [[-1.1982,  0.0976, -0.2922],
         [-1.1982,  0.0976, -0.2922],
         [-1.1982,  0.0976, -0.2922]]])


In [32]:
result = 65.33333333333333
rounded_result = round(result, 2)
print(rounded_result)

65.33


In [37]:
img_features_1 = [1, 2, 3]
img_features_2 = [4, 5, 6]
img_features_3 = []
# 将两个list合并成一个list
img_features = img_features_1 + img_features_2 + img_features_3
print(img_features)

[1, 2, 3, 4, 5, 6]
