In [6]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])

print(a)

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [12]:
print(np.stack((a, b), axis=0).shape)
c = np.stack((a, b), axis=0)
print(c )
print("\n\n")


print(np.stack((a, b), axis=1).shape)
d = np.stack((a, b), axis=1)
print(d)
print("\n\n")


print(np.stack((a, b), axis=2).shape)
e = np.stack((a, b), axis=2)
print(e)
print("\n\n")


(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]



(3, 2, 3)
[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]

 [[ 7  8  9]
  [77 88 99]]]



(3, 3, 2)
[[[ 1 11]
  [ 2 22]
  [ 3 33]]

 [[ 4 44]
  [ 5 55]
  [ 6 66]]

 [[ 7 77]
  [ 8 88]
  [ 9 99]]]





In [1]:
import torch

torch.cuda.is_available()