In [6]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])

print(a)

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [12]:
print(np.stack((a, b), axis=0).shape)
c = np.stack((a, b), axis=0)
print(c )
print("\n\n")


print(np.stack((a, b), axis=1).shape)
d = np.stack((a, b), axis=1)
print(d)
print("\n\n")


print(np.stack((a, b), axis=2).shape)
e = np.stack((a, b), axis=2)
print(e)
print("\n\n")


(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]



(3, 2, 3)
[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]

 [[ 7  8  9]
  [77 88 99]]]



(3, 3, 2)
[[[ 1 11]
  [ 2 22]
  [ 3 33]]

 [[ 4 44]
  [ 5 55]
  [ 6 66]]

 [[ 7 77]
  [ 8 88]
  [ 9 99]]]





In [2]:
import torch

torch.cuda.is_available()

/home/sswang/anaconda3/envs/img_matching/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


True

In [6]:
list1 = [
    [
        0.82080078125,
        -0.31982421875,
        0.450927734375,
        -0.86279296875,
        -0.71337890625
        ],
    [
        -0.28271484375,
        0.61279296875,
        0.0970458984375,
        -0.08740234375,
        0.9873046875]]


list2 = [
    [
        0.82080078125,
        -0.31982421875,
        0.450927734375,
        -0.86279296875,
        -0.71337890625
        ],
    [
        -0.28271484375,
        0.61279296875,
        0.0970458984375,
        -0.08740234375,
        0.9873046875]]

tensor1 = torch.tensor(list1)
tensor2 = torch.tensor(list2)

concatenated_tensor = torch.cat((tensor1, tensor2), dim=0)
print(concatenated_tensor)

tensor([[ 0.8208, -0.3198,  0.4509, -0.8628, -0.7134],
        [-0.2827,  0.6128,  0.0970, -0.0874,  0.9873],
        [ 0.8208, -0.3198,  0.4509, -0.8628, -0.7134],
        [-0.2827,  0.6128,  0.0970, -0.0874,  0.9873]])
